### ISSUE TITLE
feat(input): allow requesting changelog by username/repo

### ISSUE THREAD

**Issue by PascalPrecht** [thoughtram/clog.thoughtram.io#2]
Currently it is required to provide a full URI in order to request a changelog. Not sure if it's planned that this site requests commits from other repository providers that GitHub, but as long we'e just relying on GitHub, it'd be nicer if I could just type in `username/repo`.

**Comment by cburgdorf** [comment]
My plan is to do some kind of smart user input parsing so that the user is free to either enter a full URL or omit the `http(s)` part or even omit the `github.com` entirely as you say.

**Comment by PascalPrecht** [comment]
:+1:
